# For more on configuring pre-commit hooks (see https://pre-commit.com/)

# TODO: remove global exclusion of tests when testing overhaul is complete
exclude: '^tests/.*'

# Force all unspecified python hooks to run python 3.8
default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    additional_dependencies: ['click==8.0.4']
    args:
    - "--line-length=99"
    - "--target-version=py38"
  - id: black
    alias: black-check
    stages: [manual]
    additional_dependencies: ['click==8.0.4']
    args:
    - "--line-length=99"
    - "--target-version=py38"
    - "--check"
    - "--diff"
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
  - id: flake8
    alias: flake8-check
    stages: [manual]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    args: [--show-error-codes, --ignore-missing-imports, --exclude dbt/include/, --install-types, --non-interactive]
    files: ^dbt/adapters/.*
  - id: mypy
    alias: mypy-check
    stages: [manual]
    args: [--show-error-codes, --pretty, --ignore-missing-imports, --exclude dbt/include/, --install-types, --non-interactive]
    files: ^dbt/adapters/.*
